Codigo/encuesta/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', view=views.index, name='index'),
    path('enviar', view=views.enviar, name='enviar')
]

Codigo/lab02/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('encuesta/', include('encuesta.urls')),
    path('operations/', include('operations.urls')),
    path('volumen/', include('volumen.urls')),
    path('admin/', admin.site.urls),
]

Codigo/operations/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', view=views.index, name='index'),
    path('respuesta/', view=views.respuesta, name='respuesta'),
]

Codigo/volumen/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', view=views.index, name='index'),
    path('calculo/', view=views.calculo, name='calculo')
]

encuesta/urls.py
from django.urls import path
from . import views


app_name = 'encuesta'


urlpatterns = [
    path('', views.index,name='index'),
    path('<int:pregunta_id>/',views.detalle,name='detalle'),
    path('<int:pregunta_id>/votar',views.votar,name='votar')
]

lab03/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('encuesta/', include('encuesta.urls'))
]

Codigo/encuesta/models.py
from django.db import models

# Create your models here.

Codigo/operations/models.py
from django.db import models

# Create your models here.

Codigo/volumen/models.py
from django.db import models

# Create your models here.

encuesta/models.py
from django.db import models

# Create your models here.
class Pregunta(models.Model):
    pregunta_texto = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date_published')

class Opcion(models.Model):
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    opcion_texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    

ventas/models.py
from django.db import models

# Create your models here.
class Direccion(models.Model):
    calle = models.CharField(max_length=50)
    numero = models.PositiveIntegerField()
    comuna = models.CharField(max_length=50) 
    ciudad = models.CharField(max_length=50)

class Proveedor(models.Model):
    codigo = models.CharField(max_length=20,unique=True)
    nombre = models.CharField(max_length=50)
    direccion = models.ForeignKey(Direccion, on_delete=models.CASCADE)
    telefono = models.CharField(max_length=9)
    pagina_web = models.URLField()

class Categoria(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField()

class Producto(models.Model):
    identificador = models.CharField(max_length=20, unique=True)
    nombre = models.CharField(max_length=100)
    precio_actual = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

class Telefono(models.Model):
    numero = models.CharField(max_length=9)

class Cliente(models.Model):
    codigo = models.CharField(max_length=8,unique=True)
    nombre = models.CharField(max_length=50)
    direccion = models.ForeignKey(Direccion,on_delete=models.CASCADE)
    telefonos = models.ManyToManyField(Telefono)


class Venta(models.Model):
    nro_factura = models.CharField(max_length=20,unique=True)
    fecha = models.DateField()
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    descuento = models.DecimalField(max_digits=5,decimal_places=2)
    monto_final = models.DecimalField(max_digits=5,decimal_places=2)
    productos = models.ManyToManyField(Producto)

class ItemVendido(models.Model):
    venta = models.ForeignKey(Venta,on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    precio = models.DecimalField(max_digits=5,decimal_places=5)
    cantidad = models.PositiveIntegerField()
    monto_total = models.DecimalField(max_digits=5,decimal_places=2)

Codigo/encuesta/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {
        'titulo': 'Formulario'
    }
    return render(request, 'encuesta/formulario.html', context)

def enviar(request):
    context = {
        'titulo': 'Respuesta',
        'nombre': request.POST['nombre'],
        'clave': request.POST['password'],
        'educacion': request.POST['educacion'],
        'nacionalidad': request.POST['nacionalidad'],
        'idiomas': request.POST.getlist('idiomas'),
        'correo': request.POST['email'],
        'website': request.POST['sitioweb'],
    }
    return render(request, 'encuesta/respuesta.html', context=context)

Codigo/operations/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'operaciones/peticion.html')

def respuesta(request):
    simbolos = {
        'suma': '+',
        'resta': '-',
        'multiplicacion': '*'
    }

    operacion = request.POST['operacion']
    num1 = int(request.POST['num1'])
    num2 = int(request.POST['num2'])
    respuesta = None
    if operacion == 'suma':
        respuesta = num1 + num2
    elif operacion == 'resta':
        respuesta = num1 - num2
    else:
        respuesta = num1 * num2

    context = {
        'operacion': operacion,
        'simbolo': simbolos[request.POST['operacion']],
        'num1': num1,
        'num2': num2,
        'respuesta': respuesta
    }
    return render(request, 'operaciones/respuesta.html', context)

Codigo/volumen/views.py
from django.shortcuts import render
import math

# Create your views here.
def index(request):
    return render(request=request, template_name='index.html')

def calculo(request):
    diametro = float(request.POST['diametro'])
    altura = float(request.POST['altura'])
    radio = diametro / 2
    volumen = math.pi * radio**2 * altura

    return render(request=request, template_name='respuesta.html', context={'volumen': volumen})

encuesta/views.py
from django.shortcuts import render
from .models import *

# Create your views here.
def index(request):
    latest_question_list = Pregunta.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list':latest_question_list
    }
    return render(request,'encuesta/index.html',context)

def detalle(request,pregunta_id):
    pregunta = Pregunta.objects.get(pk=pregunta_id)
    context = {
        'pregunta':pregunta
    }
    
    return render(request,'encuesta/detalle.html',context)

def votar(request,pregunta_id):
    pregunta = Pregunta.objects.get(pk=pregunta_id)
    opcionSeleccionada = pregunta.opcion_set.get(pk=request.POST['opcion'])
    opcionSeleccionada.votos += 1
    opcionSeleccionada.save()
    context = {
        'pregunta':pregunta
    }
    return render(request,'encuesta/resultados.html',context)

ventas/views.py
from django.shortcuts import render

# Create your views here.

Codigo/encuesta/templates/encuesta/formulario.html
<h2>{{ titulo }}</h2>
<form action="{% url 'enviar' %}" method="POST">
    {% csrf_token %}
    Nombre:
    <input type="text" name="nombre" maxlength="50" /> <br>
    Contraseña:
    <input type="password" name="password" /> <br>
    Educación:
    <select name="educacion" >
        <option value="sin estudios">Sin estudios</option>
        <option value="educacion-obligatoria" selected>Educación Obligatoria</option>
        <option value="formacion-profesional">Formacion Profesional</option>
        <option value="universidad">Universidad</option>
    </select>
    Nacionalidad:
    <input type="radio" name="nacionalidad" value="hispana"> Hispana
    <input type="radio" name="nacionalidad" value="otra"> Otra <br>
    Idiomas:
    <input type="checkbox" name="idiomas" value="español" checked> Español
    <input type="checkbox" name="idiomas" value="ingles" checked> Ingles
    <input type="checkbox" name="idiomas" value="frances" checked> Frances
    <input type="checkbox" name="idiomas" value="aleman" checked> Aleman <br>
    Email:
    <input type="email" name="email" /> <br>
    Sitio web:
    <input type="text" name="sitioweb" /> <br>
    <input type="submit" />
</form>

Codigo/encuesta/templates/encuesta/respuesta.html
<h2>{{ titulo }}</h2>
<p>Nombre: {{ nombre }}</p>
<p>Clave: {{ clave }}</p>
<p>Educación: {{ educacion }}</p>
<p>Nacionalidad: {{ nacionalidad }}</p>
<p>Idiomas:</p>
<ul>
    {% for item in idiomas %}
    <li>{{ item }}</li>
    {% endfor %}
</ul>
<p>Email: {{ correo }}</p>
<p>Sitio web: {{ website }}</p>

Codigo/operations/templates/operaciones/peticion.html
<h1>Ingreso de datos</h1>
<form action="{% url 'respuesta' %}" method="post">
    {% csrf_token %}
    Ingrese el 1er numero
    <input type="number" step="1" name="num1" /> <br>
    Ingrese el 2do numero
    <input type="number" step="1" name="num2" /> <br>

    Qué tipo de operación desea:
    <select name="operacion">
        <option value="suma">Suma</option>
        <option value="resta">Resta</option>
        <option value="multiplicacion">Multiplicacion</option>
    </select>
    <br>
    <input type="submit">
</form>

Codigo/operations/templates/operaciones/respuesta.html
<h2>Respuesta</h2>

<h3>Operación: {{ operacion }}</h3>
<h3>{{ num1 }} {{ simbolo }} {{ num2 }} = {{respuesta }}</h3>

Codigo/volumen/templates/index.html
<h1>Calculo de volumen de un cilindro</h1>

<form action="{% url 'calculo' %}" method="POST">
    {% csrf_token %}
    introduzca el diametro: 
    <input type="number" step="0.01" name="diametro" /> <br>
    Introduzca la altura:
    <input type="number" step="0.01" name="altura" /> <br>
    
    <br>
    <input type="submit" value="Calcular">
</form>

Codigo/volumen/templates/respuesta.html
<h2>El volumen del cilindro es: {{ volumen }} metros cúbicos</h2>

encuesta/templates/encuesta/detalle.html
<h1>{{ pregunta.pregunta_texto }}</h1>

<form action="{% url 'encuesta:votar' pregunta.id %}" method="post">
    {% csrf_token %}
    {% for opcion in pregunta.opcion_set.all %}
        <input type="radio" name="opcion" id="opcion{{ forloop.counter }}" value="{{ opcion.id}}">
        <label for="opcion{{forloop.counter }}">{{ opcion.opcion_texto }}</label><br>
    {% endfor %}
    <input type="submit" value="votar">
</form>
<a href="{% url 'encuesta:index' %}">Ver Preguntas</a>

encuesta/templates/encuesta/index.html
<h1>Encuesta</h1>
{% if latest_question_list %}
    <ul>
        {% for pregunta in latest_question_list %}
            <li>
                <a href="/encuesta/{{pregunta.id}}">
                    {{pregunta.pregunta_texto}}
                </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No hay registros</p>
{% endif %}

encuesta/templates/encuesta/resultados.html
<h1>{{ pregunta.pregunta_texto }}</h1>
<ul>
    {%for opcion in pregunta.opcion_set.all %}
        <li>{{opcion.opcion_texto }} -- {{opcion.votos }} voto{{ opcion.votos|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'encuesta:detalle' pregunta.id %}">Votar de nuevo</a>
<a href="{% url 'encuesta:index' %}">Ver Preguntas</a>